version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
  mvc:
    image: ${DOCKER_REGISTRY-}mvc
    build:
      context: .
      dockerfile: src/mvc/Dockerfile
  idp:
    image: ${DOCKER_REGISTRY-}idp
    build:
      context: .
      dockerfile: src/IdentityServerAspNetIdentity/Dockerfile
  postgres:
    image: postgres
    container_name: Postgres
